version: "3"
services:
  app:
    container_name: "app"
    build: .
    working_dir: /app
    ports:
      - 5000:5000
    command: bash -c "sleep 5  && npm start"
    depends_on:
      - database

  database:
    container_name: database
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: superuserpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1pass
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

    ports:
      - 27018:27018

networks:
  ovl_net:
    external:
      name: mynet
